Mirantis/kostyor

kostyor/cli/kostyor_cli/main.py, kostyor/conf.ini
Kostyor client cannot find the conf.ini file so it uses default
host and port.
Add environmental variables for host and port to which Kostyor client
should send requests.
=> Fix error with reading config in Kostyor client.

kostyor/rest_api.py, kostyor/tests/unit/rest_api/test.py
REST API method 'discover_cluster' cannot get request data - auth_url, username, password, etc. Need to fix this issue and to cover 'discover_cluster' with unit tests.
=> Fix REST API method 'discover_cluster'

.gitignore
So far `.gitignore` doesn't cover a lot of temporary files occured
developing Python project. For instance, it doesn't cover *.pyc files
and swap/backup files of popular text editors.
This commit uses `.gitignore` from OpenStack cookiecutter project that
covers all popular cases.
[1] https://github.com/openstack-dev/cookiecutter
=> Use .gitignore from cookiecutter project

kostyor/db/api.py, kostyor/tests/unit/test_db_api.py
Currently there're two issues with that endpoint:
* It uses DBAPI.get_discovery_methods() without arguments but it
does receive one.
* It expects DBAPI.get_discovery_methods() to return a list of
supported discovery methods, but it returns a dictionary instead.
The fix for the first one is to get rid of unused argument, and for the
second one - return a list instead of dictionary. The funny thing is, we
have a correct mock in tests.. it's a production code that's  broken.
=> Fix /discovery-methods endpoint

kostyor/rest_api.py
Since commit [1] we don't need "/cluster-list" endpoint anymore. From now
on "/clusters" endpoint is used instead.
[1] https://github.com/sc68cal/Kostyor-cli/commit/8fdab037cbce4565e581f26d6d5de42820ba9afa
=> Remove deprecated /cluster-list endpoint

contrib/openapi.yml, tox.ini
OpenAPI is a good way to define a RESTful API which allows both humans
and computers to discover and understand the capabilities of the service
without access to source code or documentation.
This commit adds an OpenAPI spec for Kostyor API. It doesn't match
current API implementation but instead proposes cosmetic enhancements to
follow best practices of RESTful API.
Last but not least, this spec provides a good opportunity to review and
discuss changes in Kostyor API.
[1]: https://openapis.org
=> Add OpenAPI [1] specification for Kostyor API

tools/run_integration.sh
run_integration.sh used to produce a failure on case-sensitive filesystems
in case when Kostyor-cli is already cloned to /tmp/Kostyor-cli. This
happened due to misspelled directory name which is "kostyor-cli",
not "Kostyor-cli".
=> Fix tools/run_integration.sh script

contrib/openapi.yml
Rename 'OpenStack environment' to 'cluster' in OpenAPI specification - according to comments for https://github.com/sc68cal/Kostyor/pull/42
=> Rename 'OpenStack environment' to 'cluster'

contrib/openapi.yml
The version constants are currently not capitalized in the code.
=> [OpenAPI] Update version constants

contrib/openapi.yml, kostyor/db/api.py, kostyor/db/models.py, kostyor/rest_api.py, kostyor/tests/unit/rest_api/test.py, kostyor/tests/unit/test_db_api.py
Add API endpoints to query out services in a cluster
and hosts that are part of a cluster.
Add DB API methods for getting services and hosts by cluster ID.
Add unit tests.
=> Add REST API endpoints '/services' and '/hosts'

contrib/openapi.yml, kostyor/common/exceptions.py, kostyor/db/api.py, kostyor/resources/__init__.py, kostyor/resources/clusters.py, kostyor/resources/upgrades.py, kostyor/rest_api.py, kostyor/tests/unit/resources/test_clusters.py, kostyor/tests/unit/resources/test_upgrades.py, kostyor/tests/unit/rest_api/test.py, kostyor/tests/unit/test_db_api.py, requirements.txt
Flask-RESTful is an extension for Flask that adds support for quickly
building REST APIs. It encourages best practices with minimal setup.
This commit introduces flask-restful dependency and implement
`/clusters` resource that lists and show OpenStack environments.
=> Introduce Flask-RESTful with Cluster resource

kostyor/resources/clusters.py, kostyor/resources/upgrades.py, kostyor/tests/unit/resources/test_clusters.py, kostyor/tests/unit/resources/test_upgrades.py, requirements.txt
It's very convenient to have schema validation for HTTP requests, since
it allows us to have rules defined declaratively and do not hardcoded in
the code.
This commit adds Cerberus schema to validation input JSONs for POST and
PUT requests to /clusters and /clusters/:id/upgrades resources.
=> Introduce schema validation for requests

kostyor/db/api.py, kostyor/resources/upgrades.py, kostyor/tests/unit/resources/test_upgrades.py, kostyor/tests/unit/test_db_api.py
PUT request on /upgrades/:id has the following mandatory payload:
{
"cluster_id": "<cluster-id>",
"action": "<action-to-perform>"
}
So far in case cluster not found it fails with 500. We need to handle
this properly and return 404 in this case. This commit introduces this.
=> PUT /upgrades/:id returns 404 if cluster not found

tox.ini
Tox shows warning "test command found but not installed in testenv"
during integration tests running. Add 'bash' to whitelist_externals
in tox.ini file to get rid of this message.
=> Fix tox warning

kostyor/db/api.py, kostyor/rest_api.py, kostyor/tests/unit/rest_api/test.py
Remove '/create-discovery-method' REST API endpoint, remove corresponding
unit tests.
Remove DB API stub for method 'create_discovery_method' since it was called
only inside deleted REST API method.
=> Remove '/create-discovery-method' endpoint

kostyor/common/exceptions.py, kostyor/db/api.py, kostyor/rest_api.py, kostyor/tests/unit/rest_api/test.py, kostyor/tests/unit/test_db_api.py
SQLAlchemy's .first() call can return an item or None,
so push the handling of that case into the DB API layer where it belongs
=> Push exception handling into the DB layer

doc/source/decision_engine.rst
This commit extends decision engine's section and shed lights onto how
it works exactly according to implementation in PR [1].
[1] https://github.com/sc68cal/Kostyor/pull/68
=> docs: How Decision Engine Works

kostyor/conf.py, kostyor/rpc/app.py, kostyor/rpc/tasks/__init__.py, kostyor/rpc/tasks/execute.py, requirements.txt
In order to control OpenStack upgrade flow, we need a way to execute
some external scripts. For instance, in case of OpenStack Ansible we
need to execute a sequence of external scripts.
This commit adds a basic RPC layer with 'execute' task that allows to
run external task and abort it if needed.
=> [WIP] Add RPC layer with execute(...) celery task

kostyor/rpc/tasks/__init__.py, kostyor/rpc/tasks/noop.py, kostyor/tests/unit/upgrades/test_engine.py, kostyor/upgrades/__init__.py, kostyor/upgrades/driver.py, kostyor/upgrades/engine.py
According to upgrade engine implementation each driver's method has to
return a Celery task. So let's introduce a 'noop' task and return it
instead of None in fake upgrade driver. That would help to do functional
testing later and allow us to do not patch some things in tests.
=> Return noop tasks instead of None in fake driver

kostyor/upgrades/driver.py, kostyor/upgrades/engine.py, kostyor/upgrades/strategy.py
These hooks allow an upgrade driver to do any prep work before a service
or host is upgraded.
=> Decision engine: Call driver pre-upgrade hooks

kostyor/tests/unit/upgrades/test_engine.py, kostyor/upgrades/__init__.py, kostyor/upgrades/driver.py, kostyor/upgrades/engine.py
The main methods of UpgradeDriver interface receive upgrade task as a
param. However, according to UpgradeEngine implementation they receive
a service instance scheduled to be upgraded (as a dict) instead.
This commit aligns the interface in order to fix engine's needs.
=> Align UpgradeDriver interface with UpgradeEngine

kostyor/rest_api.py, kostyor/tests/unit/rest_api/test.py
Catch drivers loading errors in 'discover_cluster' REST API method.
Add unit test.
=> Catch discovery driver loading errors

kostyor/rest_api.py, kostyor/tests/unit/rest_api/test.py
The '/upgrade-status' endpoint seems to be nowhere used. It order to
maintain simplicity, let's remove this endpoint and use '/upgrades'
resources instead to retrieve any information about upgrades.
=> Remove /upgrade-status/ endpoint since it's unused

.travis.yml, kostyor/conf.py, requirements.txt
Since Celery 4.x the SQLA transport has been dropped so we need to move
away from SQLA transport. This commit changes backend transport from
SQLA to Redis.
=> Use Redis as Celery backend

kostyor/rpc/app.py, kostyor/tests/unit/rpc/test_app.py
Each Kostyor driver may provide own set of Celery tasks that needs to be
executed. The thing is, we know nothing about those tasks so a celery
worker will simply fail with message "task not found". In order to fix
that we need to load them into worker's memory on start time.
This commit adds drivers loading into memory 'app.autodiscover_tasks' in
order to avoid cyclic imports. The important thing here is that we can't
use 'stevedore' in this case due to its try to import found modules
immediately.
=> celery worker: load drivers' tasks on start

kostyor/tests/unit/upgrades/test_engine.py, kostyor/upgrades/drivers/base.py, kostyor/upgrades/engine.py
It's not always possible to do OpenStack upgrades on node-by-node
service-by-service basis. Sometimes we need to do some preparation
steps before running upgrade. For instance, in case of OpenStack
Ansible we need to migrate user configurations to newer version,
update repo containers and so on.
So the idea of 'pre_upgrade_hook' is to provide this sort of tasks
before running an actual upgrade.
=> Add 'pre_upgrade_hook' to upgrade driver interface

kostyor/rpc/tasks/execute.py
It's usually very important to pass current working directory for
executables. For instance, OpenStack Ansible's 'bootstrap-ansible.sh'
script use current working directory to get a path to one of the
playbooks. Hence, if we run it programmatically and do not pass CWD that
points to /opt/openstack-ansible - the task will fail.
=> Extend 'execute' task with 'cwd' argument

kostyor/tests/unit/upgrades/test_engine.py, kostyor/upgrades/drivers/base.py, kostyor/upgrades/drivers/noop.py, kostyor/upgrades/engine.py, setup.cfg
Working on new upgrade engine, it was turned out that current driver
interface is closely tied to node-by-node approach. If we want to have
single driver interface for various engines it needs to be redesigned,
otherwise we will end up with having different interfaces for different
engine.
In this patch we change driver interface and get rid of a lot of its
methods (as we don't know yet which signature they are going to have).
We only have experience with running upgrades and here we are sure,
it ought to be:
start(self, service, hosts)
where:
* `service` - a service to be upgraded
* `hosts` - a list of hosts to run upgrade on
With new approach we are focused on upgrading services no matter which
hosts they are running.
=> Rethink upgrade driver interface

kostyor/resources/upgrades.py, kostyor/tests/unit/resources/test_upgrades.py, kostyor/upgrades/drivers/base.py
So far there's no way to propagate any parameters to upgrade drivers
from API (or CLI), that's why such drivers as kostyor-openstack-ansible
requires to hardcode path to OpenStack Ansible root.
This commit implements an ability to pass additional key-value
parameters received in API call to upgrade driver __init__ method, so it
will be accessible later by driver implementations.
=> Propagate parameters to upgrade driver

.gitignore, kostyor/resources/clusters.py, kostyor/tests/unit/resources/test_clusters.py
Kostyor's API endpoints `/clusters` is used to respond with the
following JSON:
{
"clusters": [
{ ... },
{ ... },
{ ... }
]
}
This format contains a redundant key `clusters`, as it does not carry
any sense. This commit removes the intermediate `clusters` key so the
output looks like:
[
{ ... },
{ ... },
{ ... }
]
Fixes #73
=> Change response format of `/clusters` endpoint

kostyor/resources/upgrades.py, kostyor/tests/unit/resources/test_upgrades.py, setup.cfg
Similar to discovery and upgrade drivers, let's make upgrade engines
pluggable and discoverable via `kostyor.engines` namespace. It might
be very useful to those who are interested in having custom
orchestration behaviour.
In order to choose a concrete engine you want to use for upgrade one
needs to pass an `engine` parameter in JSON payload:
POST /upgrades HTTP/1.1
{
"engine": "node-by-node",
"driver": "openstack-ansible",
"parameters": {
"root": "..."
}
}
=> Make upgrade engines pluggable
